// src/components/ThemeToggle.tsx
import { Moon, Sun } from 'lucide-react'
import { Button } from './ui/button'
import { useTheme } from './ThemeProvider'

export function ThemeToggle() {
  const { theme, setTheme } = useTheme()

  return (
    <Button
      variant="outline"
      size="icon"
      onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}
      className="relative"
    >
      <Sun className="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
      <Moon className="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
      <span className="sr-only">Toggle theme</span>
    </Button>
  )
}

// src/components/ThemeToggle.svelte
<script lang="ts">
  import { getContext } from 'svelte'
  import { Moon, Sun } from 'lucide-svelte'
  import Button from './ui/button/Button.svelte'

  const theme = getContext('theme')

  const toggleTheme = () => {
    theme.update((current: 'light' | 'dark') => current === 'light' ? 'dark' : 'light')
  }
</script>

<Button variant="ghost" size="icon" on:click={toggleTheme}>
  {#if $theme === 'light'}
    <Moon class="h-5 w-5 transition-transform duration-200" />
  {:else}
    <Sun class="h-5 w-5 transition-transform duration-200" />
  {/if}
  <span class="sr-only">Toggle theme</span>
</Button>
